# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20160508_0656'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agency',
            table='agency_agency',
        ),
        migrations.AlterModelTable(
            name='closeddate',
            table='agency_closeddate',
        ),
        migrations.AlterModelTable(
            name='dispatchcenter',
            table='agency_dispatchcenter',
        ),
        migrations.AlterModelTable(
            name='period',
            table='agency_period',
        ),
        migrations.AlterModelTable(
            name='region',
            table='agency_region',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='agency_theme',
        ),
    ]
