# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_agency_dispatchers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agency',
            table='core_agency',
        ),
        migrations.AlterModelTable(
            name='closeddate',
            table='core_closeddate',
        ),
        migrations.AlterModelTable(
            name='dispatchcenter',
            table='core_dispatchcenter',
        ),
        migrations.AlterModelTable(
            name='period',
            table='core_period',
        ),
        migrations.AlterModelTable(
            name='region',
            table='core_region',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='core_theme',
        ),
    ]
