# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:56
from __future__ import unicode_literals

import core.aws.s3_filefield
from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={b'unique': b'A user with that username already exists.'}, help_text=b'Required. 255 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(b'^[\\w.@+-]+$', b'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name=b'username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name=b'first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name=b'last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name=b'email address')),
                ('is_staff', models.BooleanField(default=False, help_text=b'Designates whether the user can log into this admin site.', verbose_name=b'staff status')),
                ('is_active', models.BooleanField(default=True, help_text=b'Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name=b'active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date joined')),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('phone_number_verification_code', models.PositiveIntegerField()),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('disarm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('device_token', models.CharField(blank=True, max_length=255, null=True)),
                ('device_endpoint_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, choices=[(b'I', b'iOS'), (b'A', b'Android'), (b'B', b'Blackberry'), (b'W', b'Windows')], max_length=2, null=True)),
                ('user_declined_push_notifications', models.BooleanField(default=False)),
                ('user_logged_in_via_social', models.BooleanField(default=False)),
                ('notify_entourage_on_alert', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('floor_level', models.IntegerField(blank=True, null=True)),
                ('location_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('accepted_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('disarmed_time', models.DateTimeField(blank=True, null=True)),
                ('pending_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'A', b'Accepted'), (b'C', b'Completed'), (b'N', b'New'), (b'P', b'Pending'), (b'U', b'Unavailable')], default=b'N', max_length=1)),
                ('initiated_by', models.CharField(choices=[(b'N', b'911'), (b'E', b'Call'), (b'T', b'Timer'), (b'Y', b'Yank'), (b'C', b'Chat'), (b'S', b'Static')], default=b'E', max_length=2)),
                ('user_notified_of_receipt', models.BooleanField(default=False, help_text=b'Indicates if a push notification has been sent to the user to notify the app that the alert has been received.')),
                ('user_notified_of_dispatcher_congestion', models.BooleanField(default=False, help_text=b'If an organization has the chat auto-responder functionality enabled, this flag is to indicate if the user has been sent the auto-responder message.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('call_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('in_bounds', models.BooleanField(default=True)),
                ('notified_entourage', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
                ('agency_dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_agency_dispatcher', to=settings.AUTH_USER_MODEL)),
                ('agency_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_agency_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('floor_level', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.Alert')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('message_sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alert')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['message_sent_time'],
            },
        ),
        migrations.CreateModel(
            name='EntourageMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('first', models.CharField(blank=True, max_length=255, null=True)),
                ('last', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('always_visible', models.BooleanField(default=False)),
                ('track_route', models.BooleanField(default=True)),
                ('notify_arrival', models.BooleanField(default=True)),
                ('notify_non_arrival', models.BooleanField(default=True)),
                ('notify_yank', models.BooleanField(default=True)),
                ('notify_called_911', models.BooleanField(default=False)),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='existing_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entourage_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntourageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'T', b'Tracking'), (b'A', b'Arrived'), (b'N', b'Non-Arrival'), (b'C', b'Cancelled'), (b'U', b'Unknown')], default=b'T', max_length=1)),
                ('travel_mode', models.CharField(choices=[(b'D', b'Driving'), (b'W', b'Walking'), (b'B', b'Bicycling'), (b'T', b'Transit'), (b'U', b'Unknown')], default=b'U', max_length=1)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('entourage_notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='MassAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, choices=[(b'AB', b'Abuse'), (b'AR', b'Arrest'), (b'AN', b'Arson'), (b'AS', b'Assault'), (b'BU', b'Burglary'), (b'CA', b'Car Accident'), (b'DI', b'Disturbance'), (b'DR', b'Drugs/Alcohol'), (b'H', b'Harassment'), (b'MH', b'Mental Health'), (b'O', b'Other'), (b'R', b'Robbery'), (b'SH', b'Shooting'), (b'S', b'Suggestion'), (b'SA', b'Suspicious Activity'), (b'T', b'Theft'), (b'V', b'Vandalism')], max_length=2, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
                ('agency_dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='NamedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialCrimeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('report_type', models.CharField(choices=[(b'AB', b'Abuse'), (b'AS', b'Assault'), (b'CA', b'Car Accident'), (b'DI', b'Disturbance'), (b'DR', b'Drugs/Alcohol'), (b'H', b'Harassment'), (b'MH', b'Mental Health'), (b'O', b'Other'), (b'RN', b'Repair Needed'), (b'S', b'Suggestion'), (b'SA', b'Suspicious Activity'), (b'T', b'Theft'), (b'V', b'Vandalism')], max_length=2)),
                ('report_audio_url', core.aws.s3_filefield.S3URLField(blank=True, help_text=b'Location of asset on S3', null=True)),
                ('report_image_url', core.aws.s3_filefield.S3URLField(blank=True, help_text=b'Location of asset on S3', null=True)),
                ('report_video_url', core.aws.s3_filefield.S3URLField(blank=True, help_text=b'Location of asset on S3', null=True)),
                ('report_latitude', models.FloatField()),
                ('report_longitude', models.FloatField()),
                ('report_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('report_anonymous', models.BooleanField(default=False)),
                ('flagged_spam', models.BooleanField(default=False)),
                ('viewed_time', models.DateTimeField(blank=True, null=True)),
                ('flagged_by_dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_by_dispatcher', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('entourage_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.EntourageSession')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[(b'E', b'Entourage'), (b'C', b'Crime Report'), (b'O', b'Other')], default=b'O', max_length=1)),
                ('read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('hair_color', models.CharField(blank=True, choices=[(b'Y', b'Blonde'), (b'BR', b'Brown'), (b'BL', b'Black'), (b'R', b'Red'), (b'BA', b'Bald'), (b'GR', b'Gray'), (b'O', b'Other')], max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True)),
                ('race', models.CharField(blank=True, choices=[(b'BA', b'Black/African Descent'), (b'WC', b'White/Caucasian'), (b'EI', b'East Indian'), (b'AS', b'Asian'), (b'LH', b'Latino/Hispanic'), (b'ME', b'Middle Eastern'), (b'PI', b'Pacific Islander'), (b'NA', b'Native American'), (b'O', b'Other')], max_length=3, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('known_allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('emergency_contact_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_contact_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_contact_phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, choices=[(b'F', b'Father'), (b'M', b'Mother'), (b'S', b'Spouse'), (b'BF', b'Boyfriend'), (b'GF', b'Girlfriend'), (b'B', b'Brother'), (b'SI', b'Sister'), (b'FR', b'Friend'), (b'O', b'Other')], max_length=2, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=b'images/profiles')),
                ('profile_image_url', core.aws.s3_filefield.S3URLField(blank=True, help_text=b'Location of asset on S3', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entouragesession',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_locations', to='core.NamedLocation'),
        ),
        migrations.AddField(
            model_name='entouragesession',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_locations', to='core.NamedLocation'),
        ),
        migrations.AddField(
            model_name='entouragesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
