# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160430_0519'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='socialcrimereport',
            managers=[
                ('geo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
