# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160508_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyuser',
            name='username',
            field=models.CharField(error_messages={b'unique': b'A user with that username already exists.'}, help_text=b'Required. 255 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[\\w.@+-]+$', b'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name=b'username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
