# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160505_0137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='socialcrimereport',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='agencyuser',
            name='username',
            field=models.CharField(error_messages={b'unique': b'A user with that username already exists.'}, help_text=b'Required. 255 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[\\w.@+-]+$', b'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name=b'username'),
        ),
    ]
