# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticdevice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staticdevice',
            table='staticdevice_staticdevice',
        ),
    ]
